### ISSUE TITLE
[Bug] /seen command

### ISSUE THREAD

**Issue by MrLouisDew** [Maxlego08/zEssentials#102]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

uekc

### Server Version

1.21.1

### Server Software

[22:21:08 INFO]: Current Purpur Version: 1.21.1-2321-2eaea6a (MC: 1.21.1)*
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.1-2315-2a50638 (MC: 1.21.1)

### zEssentials Version

[22:21:18 INFO]: zEssentials version 1.0.1.1

### zMenu Version

[22:21:31 INFO]: zMenu version 1.0.3.5

### What happened?

When entering /seen <player>, shows the requested information, but also an error message.

### Steps to reproduce the issue

1. Enter the command /seen <player> (for exmaple: /seen Louis_Dew)
2. See in chat that the message also comes with an error message.
3. See in console an error message.

### Full Server Log

https://mclo.gs/RUDhida

### Error (optional)

```shell
[22:19:58 INFO]: Louis_Dew issued server command: /seen Louis_Dew
[22:19:58 INFO]: [zEssentials] Executing SQL: SELECT * FROM zessentials_users WHERE `unique_id` = ?
[22:19:58 INFO]: [zEssentials] Executing SQL: SELECT * FROM zessentials_user_play_times WHERE `unique_id` = ?
[22:19:58 WARN]: java.lang.NullPointerException: date must not be null
[22:19:58 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:259)
[22:19:58 WARN]:        at java.base/java.util.Calendar.setTime(Calendar.java:1801)
[22:19:58 WARN]:        at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:978)
[22:19:58 WARN]:        at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:971)
[22:19:58 WARN]:        at java.base/java.text.DateFormat.format(DateFormat.java:378)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.module.modules.SanctionModule.seen(SanctionModule.java:384)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.commands.commands.sanction.CommandSeen.lambda$perform$0(CommandSeen.java:27)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.zutils.utils.commands.VCommand.lambda$fetchUniqueId$8(VCommand.java:546)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.storage.storages.SqlStorage.fetchUniqueId(SqlStorage.java:325)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.zutils.utils.commands.VCommand.fetchUniqueId(VCommand.java:539)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.commands.commands.sanction.CommandSeen.perform(CommandSeen.java:27)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.zutils.utils.commands.VCommand.safelyPerformCommand(VCommand.java:460)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.zutils.utils.commands.VCommand.prePerform(VCommand.java:396)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.commands.ZCommandManager.processRequirements(ZCommandManager.java:112)
[22:19:58 WARN]:        at zEssentials-1.0.1.1 (4).jar//fr.maxlego08.essentials.commands.ZCommandManager.onCommand(ZCommandManager.java:72)
[22:19:58 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:19:58 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[22:19:58 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[22:19:58 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
[22:19:58 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[22:19:58 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[22:19:58 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[22:19:58 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[22:19:58 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451)
[22:19:58 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:358)
[22:19:58 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:345)
[22:19:58 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:340)
[22:19:58 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297)
[22:19:58 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271)
[22:19:58 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:19:58 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[22:19:58 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[22:19:58 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
[22:19:58 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[22:19:58 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[22:19:58 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
[22:19:58 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
[22:19:58 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[22:19:58 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510)
[22:19:58 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517)
[22:19:58 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362)
[22:19:58 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[22:19:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/e4f2e367-8793-4aa9-bb54-e116ceb8566f

**Comment by InvisibleSpiders** [comment]
This command is still not working.

Server version 1.21.3, but was also not working in 1.21.1. 
Plugin version 1.0.1.5, and prior version same thing. 

No errors, but you do get this in the chat when you type the command: 
'You must execute the command like this: /seen <player>'
