### ISSUE TITLE
Checking Players Homes

### ISSUE THREAD

**Issue by Scrawble** [Maxlego08/zEssentials#112]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I already searched on this [Github page](https://github.com/Maxlego08/zEssentials/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this or if the feature was already suggested.

### Discord Username (optional)

Scrawble

### Describe your suggestions

Allow for staff to see and telport to other players homes /home pawkyy:<name>

**Comment by Scrawble** [comment]
[19:52:01 INFO]: Scrawble issued server command: /tp pawkyy
[19:52:01 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getLocation()" because "targetPlayer" is null
[19:52:01 WARN]:        at zEssentials-1.0.1.1 (1).jar//fr.maxlego08.essentials.commands.commands.teleport.CommandTeleport.perform(CommandTeleport.java:33)
[19:52:01 WARN]:        at zEssentials-1.0.1.1 (1).jar//fr.maxlego08.essentials.zutils.utils.commands.VCommand.safelyPerformCommand(VCommand.java:460)
[19:52:01 WARN]:        at zEssentials-1.0.1.1 (1).jar//fr.maxlego08.essentials.zutils.utils.commands.VCommand.prePerform(VCommand.java:396)
[19:52:01 WARN]:        at zEssentials-1.0.1.1 (1).jar//fr.maxlego08.essentials.commands.ZCommandManager.processRequirements(ZCommandManager.java:112)
[19:52:01 WARN]:        at zEssentials-1.0.1.1 (1).jar//fr.maxlego08.essentials.commands.ZCommandManager.onCommand(ZCommandManager.java:72)
[19:52:01 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:52:01 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[19:52:01 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[19:52:01 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[19:52:01 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[19:52:01 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[19:52:01 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[19:52:01 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[19:52:01 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[19:52:01 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[19:52:01 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[19:52:01 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[19:52:01 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2224)
[19:52:01 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2198)
[19:52:01 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:52:01 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[19:52:01 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[19:52:01 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1559)
[19:52:01 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:203)
[19:52:01 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[19:52:01 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1536)
[19:52:01 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1529)
[19:52:01 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[19:52:01 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1488)
[19:52:01 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1495)
[19:52:01 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1340)
[19:52:01 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
[19:52:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)


sends fat error when they are offline
