### ISSUE TITLE
1.20.6 support hologram

### ISSUE THREAD

**Issue by Ziut3k-dev** [Maxlego08/zEssentials#13]
[22:59:07] [Server thread/ERROR]: Command exception: /hologram create TEXT a
org.bukkit.command.CommandException: Unhandled exception executing command 'hologram' in plugin zEssentials v1.0.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R3/CraftWorld
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.nms.r3_1_20.CraftHologram.create(CraftHologram.java:75) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.hologram.HologramModule.create(HologramModule.java:135) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.commands.commands.hologram.CommandHologramCreate.perform(CommandHologramCreate.java:32) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.zutils.utils.commands.VCommand.safelyPerformCommand(VCommand.java:448) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.zutils.utils.commands.VCommand.prePerform(VCommand.java:384) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.commands.ZCommandManager.processRequirements(ZCommandManager.java:112) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.commands.ZCommandManager.onCommand(ZCommandManager.java:76) ~[Essentials-1.0.9.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 26 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R3.CraftWorld
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.nms.r3_1_20.CraftHologram.create(CraftHologram.java:75) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.hologram.HologramModule.create(HologramModule.java:135) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.commands.commands.hologram.CommandHologramCreate.perform(CommandHologramCreate.java:32) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.zutils.utils.commands.VCommand.safelyPerformCommand(VCommand.java:448) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.zutils.utils.commands.VCommand.prePerform(VCommand.java:384) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.commands.ZCommandManager.processRequirements(ZCommandManager.java:112) ~[Essentials-1.0.9.jar:?]
	at Essentials-1.0.9.jar/fr.maxlego08.essentials.commands.ZCommandManager.onCommand(ZCommandManager.java:76) ~[Essentials-1.0.9.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 26 more

**Comment by Maxlego08** [comment]
Fixed !
