### ISSUE TITLE
i cannot change port database

### ISSUE THREAD

**Issue by itorz7** [Maxlego08/zEssentials#144]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Server Version

1.21.4

### Server Software

[19:58:17 INFO]: Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version

### zEssentials Version

error

### zMenu Version

no

### What happened?

![image](https://github.com/user-attachments/assets/ced42295-35c8-4bf5-a0d0-75a319539145)

### Steps to reproduce the issue

just change port database

### Full Server Log

no

### Error (optional)

```shell
[19:54:16 ERROR]: Error occurred while enabling zEssentials v1.0.1.4 (Is it up to date?)
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/fr.maxlego08.essentials.libs.sarah.HikariDatabaseConnection.initializeDataSource(HikariDatabaseConnection.java:83) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/fr.maxlego08.essentials.libs.sarah.HikariDatabaseConnection.<init>(HikariDatabaseConnection.java:34) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/fr.maxlego08.essentials.storage.storages.SqlStorage.<init>(SqlStorage.java:117) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/fr.maxlego08.essentials.storage.ZStorageManager.<init>(ZStorageManager.java:34) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/fr.maxlego08.essentials.ZEssentialsPlugin.onEnable(ZEssentialsPlugin.java:204) ~[zEssentials-1.0.1.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:779) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:526) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:356) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:861) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:234) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[zEssentials-1.0.1.4.jar:?]
        ... 19 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:139) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:980) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:851) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:234) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[zEssentials-1.0.1.4.jar:?]
        ... 19 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:139) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:980) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:851) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:234) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[zEssentials-1.0.1.4.jar:?]
        at zEssentials-1.0.1.4.jar/com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[zEssentials-1.0.1.4.jar:?]
        ... 19 more
```

**Comment by Maxlego08** [comment]
Hey ! Thx its fixed !
