### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by SinonCute** [Maxlego08/zEssentials#145]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

sinoncute

### Server Version

1.21.4

### Server Software

This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.3-3-52a0590 (MC: 1.21.3)

### zEssentials Version

zEssentials version 1.0.1.5

### zMenu Version

(zMenu) Version du plugin: 1.0.3.5

### What happened?

broken the SQL

### Steps to reproduce the issue

Start the server

### Full Server Log

https://mclo.gs/Rwiwatw

### Error (optional)

```shell
[02:10:59 WARN]: java.sql.SQLSyntaxErrorException: Unknown column 'No reason' in 'DEFAULT'
[02:10:59 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112)
[02:10:59 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[02:10:59 WARN]:        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:590)
[02:10:59 WARN]:        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:335)
[02:10:59 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:359)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.libs.sarah.requests.AlterRequest.execute(AlterRequest.java:51)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.libs.sarah.SchemaBuilder.execute(SchemaBuilder.java:648)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.libs.sarah.MigrationManager.lambda$execute$2(MigrationManager.java:58)
[02:10:59 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.libs.sarah.MigrationManager.execute(MigrationManager.java:54)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.storage.storages.SqlStorage.<init>(SqlStorage.java:161)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.storage.ZStorageManager.<init>(ZStorageManager.java:34)
[02:10:59 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.ZEssentialsPlugin.onEnable(ZEssentialsPlugin.java:204)
[02:10:59 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[02:10:59 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[02:10:59 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[02:10:59 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[02:10:59 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[02:10:59 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[02:10:59 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[02:10:59 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[02:10:59 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[02:10:59 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[02:10:59 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[02:10:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Maxlego08** [comment]
Can you give me your database file plz

**Comment by SinonCute** [comment]
[zessentials.zip](https://github.com/user-attachments/files/18117594/zessentials.zip)

**Comment by SinonCute** [comment]
I think this is the reason why https://stackoverflow.com/questions/68821512/mysql-longtext-cant-have-a-default-value

**Comment by Maxlego08** [comment]
ho you right, i will fix that now !

**Comment by Maxlego08** [comment]
@SinonCute its fix ! i can send you the jar on discord
