### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by Zayedq7** [Maxlego08/zEssentials#37]
when using /tp <playername> you still get this message
![image](https://github.com/user-attachments/assets/6dfe6548-72d9-4d30-b42a-ae56f345f164)

and add /tp <player1> <player2> what this will do is teleport player1 to player2

**Comment by Zayedq7** [comment]
and i just got this random error

[23:39:34 INFO]: Dragonsmasher123 issued server command: /rg info
[23:39:55 INFO]: [WorldGuard] Region data changes made in 'world' have been background saved
[23:40:24 WARN]: java.sql.SQLException: No operations allowed after statement closed.
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.StatementImpl.clearWarnings(StatementImpl.java:410)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:999)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:988)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.requests.InsertRequest.execute(InsertRequest.java:54)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.SchemaBuilder.execute(SchemaBuilder.java:605)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.Repository.insert(Repository.java:59)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.Repository.insert(Repository.java:53)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.repositeries.CommandsRepository.insert(CommandsRepository.java:17)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.storages.SqlStorage.lambda$insertCommand$18(SqlStorage.java:374)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.zutils.utils.StorageHelper.lambda$async$0(StorageHelper.java:31)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:51)
[23:40:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:103)
[23:40:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:40:24 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:40:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:40:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:40:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:40:24 WARN]: Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
[23:40:24 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[23:40:24 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[23:40:24 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[23:40:24 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[23:40:24 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:340)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.StatementImpl.clearWarnings(StatementImpl.java:405)
[23:40:24 WARN]:        ... 17 more
[23:40:24 WARN]: java.sql.SQLException: Failed to execute upsert: No operations allowed after statement closed.
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.requests.InsertRequest.execute(InsertRequest.java:67)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.SchemaBuilder.execute(SchemaBuilder.java:605)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.Repository.insert(Repository.java:59)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.Repository.insert(Repository.java:53)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.repositeries.CommandsRepository.insert(CommandsRepository.java:17)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.storages.SqlStorage.lambda$insertCommand$18(SqlStorage.java:374)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.zutils.utils.StorageHelper.lambda$async$0(StorageHelper.java:31)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:51)
[23:40:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:103)
[23:40:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:40:24 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:40:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:40:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:40:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:40:24 WARN]: Caused by: java.sql.SQLException: No operations allowed after statement closed.
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.StatementImpl.clearWarnings(StatementImpl.java:410)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:999)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:988)
[23:40:24 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.requests.InsertRequest.execute(InsertRequest.java:54)
[23:40:24 WARN]:        ... 13 more
[23:40:24 WARN]: Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
[23:40:24 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[23:40:24 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[23:40:24 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[23:40:24 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[23:40:24 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:340)
[23:40:24 WARN]:        at com.mysql.cj.jdbc.StatementImpl.clearWarnings(StatementImpl.java:405)
[23:40:24 WARN]:        ... 17 more

**Comment by Zayedq7** [comment]
not sure 100% sure if its zEssentials related tho
