### ISSUE TITLE
error on command usage /r

### ISSUE THREAD

**Issue by Zayedq7** [Maxlego08/zEssentials#55]
[13:04:45 INFO]: qjade issued server command: /r tpa rn
[13:04:46 INFO]: qjade issued server command: /r tpa rn
[13:04:46 WARN]: java.sql.SQLException: No operations allowed after statement closed.
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.StatementImpl.clearWarnings(StatementImpl.java:410)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:999)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:988)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.requests.InsertRequest.execute(InsertRequest.java:54)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.SchemaBuilder.execute(SchemaBuilder.java:605)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.Repository.insert(Repository.java:59)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.Repository.insert(Repository.java:53)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.repositeries.CommandsRepository.insert(CommandsRepository.java:17)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.storages.SqlStorage.lambda$insertCommand$18(SqlStorage.java:374)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.zutils.utils.StorageHelper.lambda$async$0(StorageHelper.java:31)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:51)
[13:04:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:103)
[13:04:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:04:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:04:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:04:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:04:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[13:04:46 WARN]: Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
[13:04:46 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[13:04:46 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[13:04:46 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[13:04:46 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[13:04:46 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:340)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.StatementImpl.clearWarnings(StatementImpl.java:405)
[13:04:46 WARN]:        ... 17 more
[13:04:46 WARN]: java.sql.SQLException: Failed to execute upsert: No operations allowed after statement closed.
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.requests.InsertRequest.execute(InsertRequest.java:67)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.SchemaBuilder.execute(SchemaBuilder.java:605)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.Repository.insert(Repository.java:59)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.Repository.insert(Repository.java:53)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.database.repositeries.CommandsRepository.insert(CommandsRepository.java:17)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.storage.storages.SqlStorage.lambda$insertCommand$18(SqlStorage.java:374)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.zutils.utils.StorageHelper.lambda$async$0(StorageHelper.java:31)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:51)
[13:04:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:103)
[13:04:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:04:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:04:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:04:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:04:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[13:04:46 WARN]: Caused by: java.sql.SQLException: No operations allowed after statement closed.
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.StatementImpl.clearWarnings(StatementImpl.java:410)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:999)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:988)
[13:04:46 WARN]:        at zEssentials-1.0.0.3.jar//fr.maxlego08.essentials.libs.sarah.requests.InsertRequest.execute(InsertRequest.java:54)
[13:04:46 WARN]:        ... 13 more
[13:04:46 WARN]: Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
[13:04:46 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[13:04:46 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[13:04:46 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[13:04:46 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[13:04:46 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:340)
[13:04:46 WARN]:        at com.mysql.cj.jdbc.StatementImpl.clearWarnings(StatementImpl.java:405)
[13:04:46 WARN]:        ... 17 more

**Comment by Maxlego08** [comment]
Please try the latest version of the plugin!
