### ISSUE TITLE
Error after typing each message

### ISSUE THREAD

**Issue by Nuyyu** [Maxlego08/zEssentials#7]
```js
[22:46:16 ERROR]: Could not pass event AsyncChatEvent to zEssentials vDEV-1.0.3
org.apache.commons.lang3.NotImplementedException: insertChatMessage is not implemented, use MYSQL storage
        at fr.maxlego08.essentials.storage.storages.JsonStorage.insertChatMessage(JsonStorage.java:276) ~[Essentials-DEV-1.0.3-all.jar:?]
        at fr.maxlego08.essentials.module.modules.ChatModule.onTalk(ChatModule.java:134) ~[Essentials-DEV-1.0.3-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor271.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:git-Plazma-"e4ca876"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:62) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:181) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:114) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2519) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$14(ServerGamePacketListenerImpl.java:2239) ~[?:?]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:27) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Maxlego08** [comment]
Plz use this zMenu version, join discord for get the jar https://discord.gg/JRdp7fbX
