### ISSUE TITLE
Conflict with Veinminer (BlockBreakEvent)

### ISSUE THREAD

**Issue by Dungjava** [Maxlego08/zEssentials#70]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Server Version

1.21.1

### Server Software

[16:53:40 INFO]: This server is running Leaf version 1.21.1-DEV-ver/1.21.1@1a9ddb5 (2024-09-01T04:13:25Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
* You are 1 version(s) behind
Download the new version at: https://github.com/Winds-Studio/Leaf

### zEssentials Version

[16:54:10 INFO]: zEssentials version 1.0.0.6
[16:54:10 INFO]: Provides an essential, core set of commands for Bukkit.
[16:54:10 INFO]: Website: https://groupez.dev/

### zMenu Version

version zMenu
[16:54:38 INFO]: zMenu version 1.0.3.4
[16:54:38 INFO]: Inventory management plugin
[16:54:38 INFO]: Website: https://groupez.dev/resources/zmenu.253
[16:54:38 INFO]: Author: Maxlego08
[16:54:38 INFO]: Contributors: mani1232, lijinhong11, Adreez, EnzoShoes, Noltox and saildrag

### What happened?

When i break block, the plugin veinminer show error up on console say about "BlockBreakEvent" and "fr.maxlego08.essentials.api.economy.Economy.getName". And i can't break all ore at same time.
Error: https://mclo.gs/y3pa1IR
Full log: https://mclo.gs/G4meuSj

### Steps to reproduce the issue

Download zEssentials, zMenu and Veinminer
Start server
Join server
Break ores

### Full Server Log

https://mclo.gs/G4meuSj

### Error (optional)

```shell
[16:40:12 ERROR]: Could not pass event BlockBreakEvent to VeinMiner v2.2.5
java.lang.NullPointerException: Cannot invoke "fr.maxlego08.essentials.api.economy.Economy.getName()" because "economy" is null
        at zEssentials-1.0.0.6.jar/fr.maxlego08.essentials.user.ZUser.getBalance(ZUser.java:369) ~[zEssentials-1.0.0.6.jar:?]
        at zEssentials-1.0.0.6.jar/fr.maxlego08.essentials.hooks.VaultEconomy.getBalance(VaultEconomy.java:96) ~[zEssentials-1.0.0.6.jar:?]
        at zEssentials-1.0.0.6.jar/fr.maxlego08.essentials.hooks.VaultEconomy.has(VaultEconomy.java:123) ~[zEssentials-1.0.0.6.jar:?]
        at VeinMiner-Bukkit-2.2.5.jar/wtf.choco.veinminer.economy.SimpleVaultEconomy.hasSufficientBalance(SimpleVaultEconomy.java:48) ~[VeinMiner-Bukkit-2.2.5.jar:?]
        at VeinMiner-Bukkit-2.2.5.jar/wtf.choco.veinminer.listener.BreakBlockListener.onBlockBreak(BreakBlockListener.java:105) ~[VeinMiner-Bukkit-2.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:280) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1941) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1555) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1533) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1526) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1484) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1491) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-1a9ddb5]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Other files, you can drag and drop them here to upload. (optional)

[archive-2024-09-02T095832Z.tar.gz](https://github.com/user-attachments/files/16835850/archive-2024-09-02T095832Z.tar.gz)

**Comment by Maxlego08** [comment]
Plz update your economy config.yml file ! 
![image](https://github.com/user-attachments/assets/c816b30a-6fa4-46b6-8512-6abbae32431a)

```yml
# List of available economies
economies:
  # Economy name
  - name: money
    # Economy display name. This name will be used to be displayed in player messages whenever possible.
    display-name: Money
    # Economy symbol
    symbol: "$"
    # Economy format
    format: "%price%$"
    # Should the economy be used for vault. Only one economy can work with vault.
    vault: true
    # The minimum number possible with this economy.
    min: -99999999999999999999999999999999999999999999999999999999999999
    # The maximum number possible with this economy.
    max: 99999999999999999999999999999999999999999999999999999999999999
    # The minimum number for /pay command
    min-pay: 0.1
    # The maximum number for /pay command
    max-pay: 999999999999999
    # Enable the ability to use /pay command with this economy
    enable-pay: true
    # Activate confirmation menu for /pay command. This menu will confirm that you really want to send money to the player
    enable-confirm-inventory: true
    # The minimum number to display the confirmation inventory, below the command will run directly
    min-confirm-inventory: 10000000
    # The format type of for numbers
    price-format: PRICE_WITH_REDUCTION

    # Economy name
  - name: coins
    # Economy display name. This name will be used to be displayed in player messages whenever possible.
    display-name: Coins
    # Economy symbol
    symbol: "⛁"
    # Economy format
    format: "%price%⛁"
    # Should the economy be used for vault. Only one economy can work with vault.
    vault: false
    # The minimum number possible with this economy.
    min: 0
    # The maximum number possible with this economy.
    max: 9999999999999999999999999
    # The minimum number for /pay command
    min-pay: 0.1
    # The maximum number for /pay command
    max-pay: 1000
    # Enable the ability to use /pay command with this economy
    enable-pay: true
    # Activate confirmation menu for /pay command. This menu will confirm that you really want to send money to the player
    enable-confirm-inventory: true
    # The minimum number to display the confirmation inventory, below the command will run directly
    min-confirm-inventory: 0
    # The format type of for numbers
    price-format: PRICE_RAW
```
