### ISSUE TITLE
Can't get location after player die

### ISSUE THREAD

**Issue by Dungjava** [Maxlego08/zEssentials#92]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

maiminhdung

### Server Version

1.20.4

### Server Software

![image](https://github.com/user-attachments/assets/0b670a08-d47c-4b42-b3b1-671025a3f661)

### zEssentials Version

![image](https://github.com/user-attachments/assets/ce6bbce2-c95f-4018-abdf-5d5250c1e8e6)

### zMenu Version

![image](https://github.com/user-attachments/assets/e9c74639-f942-4925-b8ca-33a9947b3c73)

### What happened?

When the player dies, there is a chance to cause "org.bukkit.entity.Player.getLocation()" and it make spam error on console ,can't /back on death either.
We have tried on 1.21.1 and still get same error so 

### Steps to reproduce the issue

1. Join server
2. Just die
3. Keep do it until get error

### Full Server Log

https://mclo.gs/lkfp6lz

### Error (optional)

```shell
[08:34:55] [Server thread/WARN]: [zEssentials] Task #1579993 for zEssentials v1.0.1.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getLocation()" because the return value of "fr.maxlego08.essentials.user.ZUser.getPlayer()" is null
	at fr.maxlego08.essentials.user.ZUser.lambda$teleport$1(ZUser.java:240) ~[zEssentials-1.0.1.0.jar:?]
	at fr.maxlego08.essentials.libs.folialib.impl.SpigotImplementation.lambda$runTimer$4(SpigotImplementation.java:161) ~[zEssentials-1.0.1.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Other files, you can drag and drop them here to upload. (optional)

[archive-2024-09-22T085150-0400.tar.gz](https://github.com/user-attachments/files/17089769/archive-2024-09-22T085150-0400.tar.gz)

**Comment by Maxlego08** [comment]
Fixed in last commit bfac3fbd10193dfe4a5f7f73b303976597ed6583
